version: '3.8'

services:
  db:
    image: postgres:17-alpine
    container_name: bookstore-db
    restart: always
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: book-store-bd
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - bookstore-network
    # Healthcheck para garantir que o banco est√° pronto antes da APP tentar conectar
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  book-store:
    image: murilodias03/book-store
    container_name: bookstore-app
    restart: on-failure
    build: .
    working_dir: /BookStore
    command: mvn spring-boot:run
    environment:
      TZ: America/Sao_Paulo
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/book-store-bd
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bookstore-network

volumes:
  postgres-data:

networks:
  bookstore-network:
    driver: bridge