cors:
  originPatterns: http://localhost:8080,http://localhost:3000

file:
  upload-dir: /home/murilo/projetos/estudo/Erudio-SpringBoot/rest-with-spring-boot-and-java/outros/arquivos

email:
  subject: "Default Subject"
  message: "Default Message"

spring:
  application:
    name: BookStore
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/book-store-bd?options=-c%20timezone=UTC
    username: postgres
    password: ${BD_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:

    show-sql: false

    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enabled: true
      mail.smtp.starttls.required: true

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

logging:
  level:
    # root: WARN
    com.murilodias03.bookstore: DEBUG

spring-doc:
  paths-to-match:
    - /person/**
    - /books/**
    - /files/**
    - /email/**
  swagger-ui:
    use-root-path: true