spring:
  application:
    name: BookStore
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/book-store-bd?options=-c%20timezone=UTC
    username: postgres
    password: B2a1r17@
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:

    show-sql: false

    open-in-view: false

logging:
  level:
    # root: WARN
    com.murilodias03.bookstore: DEBUG